// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"attendance/api/auth"
	"attendance/api/restHandler"
	"attendance/api/router"
	"attendance/repository"
	"attendance/services"
	"github.com/go-pg/pg"
)

// Injectors from wire.go:

func InitializeApp(db *pg.DB) *router.MUXRouterImpl {
	repositoryImpl := repository.NewRepositoryImpl(db)
	homeServiceImpl := services.NewHomeServiceImpl(repositoryImpl)
	authServiceImpl := auth.NewAuthServiceImpl(repositoryImpl)
	homeImpl := restHandler.NewHomeImpl(homeServiceImpl, authServiceImpl)
	loginImpl := restHandler.NewLoginImpl(repositoryImpl, authServiceImpl)
	newUserServiceImpl := services.NewNewUserServiceImpl(repositoryImpl)
	newUserImpl := restHandler.NewNewUserImpl(newUserServiceImpl, authServiceImpl)
	punchInOutServiceImpl := services.NewPunchInOutServiceImpl(repositoryImpl)
	punchInOutImpl := restHandler.NewPunchInOutImpl(punchInOutServiceImpl, authServiceImpl)
	teacherAttendanceServiceImpl := services.NewTeacherAttendanceServiceImpl(repositoryImpl)
	teacherAttendanceImpl := restHandler.NewTeacherAttendanceImpl(teacherAttendanceServiceImpl, authServiceImpl)
	classAttendanceImpl := services.NewClassAttendanceImpl(repositoryImpl)
	restHandlerClassAttendanceImpl := restHandler.NewClassAttendanceImpl(classAttendanceImpl, authServiceImpl)
	studentAttendanceServiceImpl := services.NewStudentAttendanceServiceImpl(repositoryImpl)
	studentAttendanceImpl := restHandler.NewStudentAttendanceImpl(studentAttendanceServiceImpl, authServiceImpl)
	fetchStatusImpl := services.NewFetchStatusImpl(repositoryImpl)
	restHandlerFetchStatusImpl := restHandler.NewFetchStatusImpl(fetchStatusImpl, authServiceImpl)
	muxRouterImpl := router.NewMUXRouterImpl(homeImpl, loginImpl, newUserImpl, punchInOutImpl, teacherAttendanceImpl, restHandlerClassAttendanceImpl, studentAttendanceImpl, restHandlerFetchStatusImpl)
	return muxRouterImpl
}
